config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show          # GET /restaurants/:id
    @restaurant = Restaurant.find(params["id"])
  end

  def new           # GET /restaurants/new
    @restaurant = Restaurant.new
  end

  def create        # POST /restaurants
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  # def edit          # GET /restaurants/:id/edit
  #   @restaurant = Restaurant.find(params[:id])
  # end

  # def update        # PATCH /restaurants/:id
  #   @restaurant = Restaurant.find(params[:id])
  #   @restaurant.update(params[:restaurant])
  # end

  # def destroy       # DELETE /restaurants/:id
  #   @restaurant = Restaurant.find(params[:id])
  #   @restaurant.destroy
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
        <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to " ", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>

    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>
<ul>
  <% @restaurants.each do |resto| %>
    <li><%= link_to(resto.name, restaurant_path(resto)) %></li>
  <% end %>
</ul>
<br>
<%= link_to "Add another restaurant", new_restaurant_path, class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>